TRUNCATE TABLE `#__clm_dwz_verbaende`;
INSERT INTO `#__clm_dwz_verbaende` VALUES ('000','0','000','Deutscher Schachbund e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('100','1','000','Badischer Schachverband');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('101','1','100','Mannheim');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('102','1','100','Heidelberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('103','1','100','Odenwald');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('104','1','100','Karlsruhe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('105','1','100','Pforzheim');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('106','1','100','Mittelbaden');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('107','1','100','Ortenau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('108','1','100','Freiburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('109','1','100','Hochrhein');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('10A','1','100','Schwarzwald');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('10B','1','100','Bodensee');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('200','2','000','Bayerischer Schachbund e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('210','2','200','Mittelfranken');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('211','2','210','Mittelfranken-Mitte');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('212','2','210','Mittelfranken-Nord');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('213','2','210','Mittelfranken-Ost');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('214','2','210','Mittelfranken-Süd');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('215','2','210','Mittelfranken-West');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('220','2','200','München');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('230','2','200','Niederbayern');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('240','2','200','BV Oberbayern e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('241','2','240','Schachkreis IN-FS');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('242','2','240','Schachkreis Inn-Chiemgau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('244','2','240','Schachkreis Zugspitze');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('250','2','200','BV Oberfranken');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('251','2','250','Kreisverband Bamberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('252','2','250','Kreisverband Bayreuth');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('253','2','250','Kreisverband Hof');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('254','2','250','Kreisverband Coburg/Neustadt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('255','2','250','Kreisverband Marktredwitz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('256','2','250','Kreisverband Lichtenfels/Kronach');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('260','2','200','Schachverband Oberpfalz e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('270','2','200','Schwaben');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('271','2','270',' Augsburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('272','2','270','Mittelschwaben');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('273','2','270','Nordschwaben');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('274','2','270','Südschwaben');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('280','2','200','Unterfranken e.V');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('281','2','280','Spessart/Untermain');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('282','2','280','Mainspessart');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('283','2','280','Haßberge-Rhön');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('284','2','280','Maindreieck');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('300','3','000','Berliner Schachverband');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('400','4','000','Hamburger Schachverband');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('500','5','000','Hessischer Schachverband');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('510','5','500','Kassel-Nordhessen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('520','5','500','Osthessen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('530','5','500','Lahn-Eder');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('540','5','500','Main-Vogelsberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('550','5','500','Frankfurt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('560','5','500','Starkenburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('570','5','500','Main-Taunus');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('580','5','500','Rhein-Taunus');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('590','5','500','Lahn');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('5A0','5','500','Bergstraße');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('600','6','000','Schachbund Nordrhein-Westfalen e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('610','6','600','SV Ruhrgebiet e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('611','6','610','Schachbezirk Bochum');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('612','6','610','Schachgemeinschaft Dortmund');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('613','6','610','Essener Schachverband e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('614','6','610','Schachbezirk Emscher-Lippe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('615','6','610','Schachbezirk Hamm');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('616','6','610','Mülheim an der Ruhr 1922 e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('617','6','610','Schachbezirk Herne - Vest');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('620','6','600','Niederrheinischer Schachverband 1901 e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('621','6','620','Schachbezirk Bergisch-Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('622','6','620','Schachbezirk Düsseldorf');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('623','6','620','Schachbezirk Duisburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('624','6','620','Linker Niederrhein');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('625','6','620','Schachbezirk Kreis Wesel e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('630','6','600','Schachverband Südwestfalen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('632','6','630','Schachbezirk Iserlohn');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('633','6','630','Schachbezirk Oberberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('634','6','630','Schachbezirk Hochsauerland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('635','6','630','Schachbezirk Sauerland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('636','6','630','Schachbezirk Siegerland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('640','6','600','Schachverband Ostwestfalen-Lippe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('641','6','640','Schachbezirk Bielefeld');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('642','6','640','Schachbezirk Hellweg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('643','6','640','Schachbezirk Lippe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('644','6','640','Schachbezirk Porta');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('645','6','640','Schachbezirk Teutoburger Wald-West');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('650','6','600','Schachverband Münsterland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('651','6','650','Schachbezirk Steinfurt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('652','6','650','Schachbezirk Borken');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('653','6','650','Schachbezirk Münster');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('660','6','600','Schachverband Mittelrhein e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('661','6','660','Aachener Schachverband 1928 e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('662','6','660','Bonn/Rhein-Sieg e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('663','6','660','Kölner Schachverband von 1920 e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('664','6','660','Schachbezirk Rur-Erft');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('665','6','660','Schachbezirk Rhein-Wupper');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('700','7','000','Niedersächsischer Schachverband e. V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('701','7','700','Bezirk 1 Hannover');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('702','7','700','Bezirk 2 Braunschweig');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('703','7','700','Bezirk 3 Südniedersachsen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('704','7','700','Bezirk 4 Lüneburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('705','7','700','Bezirk 5 Oldenburg-Ostfriesland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('706','7','700','Bezirk 6 Osnabrück-Emsland');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('800','8','000','SB Rheinland-Pfalz e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('810','8','800','Schachverband Rheinland e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('811','8','810','Bezirk I Rhein-Ahr-Mosel');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('812','8','810','Bezirk II Rhein-Nahe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('813','8','810','Bezirk III Rhein-Westerwald');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('815','8','810','Bezirk IV Trier');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('820','8','800','SB Rheinhessen e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('830','8','800','Pfälzischer Schachbund e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('831','8','830','Bezirk I Kaiserslautern');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('832','8','830','Bezirk II Ludwigshafen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('833','8','830','Bezirk III Neustadt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('834','8','830','Bezirk IV Landau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('835','8','830','Bezirk V Pirmasens');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('836','8','830','Bezirk VI Ramstein');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('900','9','000','Saarländischer Schachverband');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('A00','A','000','SVB Schleswig-Holstein');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('A01','A','A00','Bezirk I Nord');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('A02','A','A00','Bezirk II West');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('A06','A','A00','Bezirk VI Kiel');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('A08','A','A00','Bezirk Ost');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('B00','B','000','Landesschachbund Bremen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C00','C','000','Schachverband Württemberg e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C01','C','C00','Bezirk Oberschwaben');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C02','C','C00','Bezirk Alb-Schwarzwald');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C03','C','C00','Bezirk Neckar-Fils');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C04','C','C00','Bezirk Ostalb');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C05','C','C00','Bezirk Stuttgart');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('C06','C','C00','Bezirk Unterland-Hohenlohe');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('D00','D','000','Schachbund Brandenburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('D10','D','D00','Cottbus');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('D20','D','D00','Frankfurt/O.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('D30','D','D00','Potsdam');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('E00','E','000','LSV Mecklenburg-Vorpommern');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('E01','E','E00','Spielbezirk West');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('E02','E','E00','Spielbezirk Mitte');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('E03','E','E00','Spielbezirk Ost');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F00','F','000','Schachverband Sachsen e.V.');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F10','F','F00','Leipzig');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F11','F','F10','Landkreis Delitzsch');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F12','F','F10','Landkreis Döbeln');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F13','F','F10','Landkreis Torgau-Oschatz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F15','F','F10','Stadt Leipzig');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F18','F','F10','Kreis Leipziger Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F19','F','F10','Muldentalkreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F20','F','F00','Dresden');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F21','F','F20','Landkreis Riesa-Großenhain');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F22','F','F20','Landkreis Sächsische Schweiz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F23','F','F20','Landkreis Kamenz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F24','F','F20','Stadt Hoyerswerda');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F25','F','F20','Weiseritzkreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F26','F','F20','Landkreis Meißen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F27','F','F20','Stadt Görlitz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F28','F','F20','Stadt Dresden');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F29','F','F20','Landkreis Löbau-Zittau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F2A','F','F20','Landkreis Bautzen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F2B','F','F20','Niederschlesischer Oberlausitzkreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F30','F','F00','Chemnitz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F31','F','F30','Landkreis Stollberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F32','F','F30','Landkreis Mittweida');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F33','F','F30','Landkreis Freiberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F34','F','F30','Landkreis Chemnitzer Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F35','F','F30','Landkreis Annaberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F36','F','F30','Stadt Chemnitz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F37','F','F30','Vogtlandkreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F38','F','F30','Stadt Zwickau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F39','F','F30','Mittlerer Erzgebirgskreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F3A','F','F30','Landkreis Zwicker Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F3B','F','F30','Stadt Plauen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('F3C','F','F30','Landkreis Aue-Schwarzenberg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('G00','G','000','LSV Sachsen-Anhalt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('G01','G','G00','Schachbezirk Dessau');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('G02','G','G00','Schachbezirk Halle');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('G03','G','G00','Schachbezirk Magdeburg');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H00','H','000','Thüringer Schachbund');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H10','H','H00','Schachbezirk Nord');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H11','H','H10','Schachkreis Kyffhäuser');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H12','H','H10','Schachkreis Eichsfeld');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H13','H','H10','Schachkreis Nordhausen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H14','H','H10','Schachkreis Unstrut-Hainich');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H15','H','H10','Schachkreis Gotha');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H20','H','H00','Schachbezirk Mitte');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H21','H','H20','Schachkreis Erfurt');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H22','H','H20','Schachkreis Weimarer Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H23','H','H20','Schachkreis Sömmerda');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H24','H','H20','Schachkreis Ilm-Kreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H25','H','H20','Schachkreis Weimar');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H30','H','H00','Schachbezirk Ost');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H31','H','H30','Schachkreis Gera');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H32','H','H30','Schachkreis Jena/Holzlandkreis');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H33','H','H30','Schachkreis Greiz');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H34','H','H30','Schachkreis Altenburger Land');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H35','H','H30','Schachkreis Saalfeld-Rudolstadt/SOK');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H40','H','H00','Schachbezirk Süd');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H41','H','H40','Schachkreis Schmalkalden-Meiningen/Suhl');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H42','H','H40','Schachkreis Sonneberg/Hildburghausen');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('H43','H','H40','Schachkreis Wartburgkreis/Eisenach');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('L00','L','000','Dt. Blinden- und Sehbehinderten-Schachbund');
INSERT INTO `#__clm_dwz_verbaende` VALUES ('M00','M','000','Schwalbe, dt. Vereinigung für Problemschach');
