<?php

/**
 * Installation der Datenbank
 * Nur erforderlich bei der ersten Installation
 * Die Erstinstallation erfolgt mit aktuellen Stand 
 * alle danach erfolgten Änderungen werden angehängt
 */
	 
//function dbinstall($collation) {

// UTF8-Test
	$utf8 = SimpleClmInstaller::_isUtf8($collation);
				
// INIT
	$tableCreate = array();
	$tableInsert = array();
		
	$engine = '';   // old: ENGINE=MyISAM
	echo "<br>dbinstall03";
	// alle Tabellen werden als key->value-Paar gespeichert
						
	$tableCreate['dwz_spieler'] = "CREATE TABLE IF NOT EXISTS `dwz_spieler` (
		`ZPS`                varchar(5)   NOT NULL default '',
		`Mgl_Nr`             char(4)      NOT NULL default '',
		`Status`             char(1)               default NULL,
		`Spielername`        varchar(40)  NOT NULL default '',
		`Spielername_G`      varchar(40)  NOT NULL default '',
		`Geschlecht`         char(1)               default NULL,
		`Spielberechtigung`  char(1)      NOT NULL default '',
		`Geburtsjahr`        year(4)      NOT NULL default '0000',
		`Letzte_Auswertung`  mediumint(6) unsigned default NULL,
		`DWZ`                smallint(4)  unsigned default NULL,
		`DWZ_Index`          smallint(3)  unsigned default NULL,
		`FIDE_Elo`           smallint(4)  unsigned default NULL,
		`FIDE_Titel`         char(2)               default NULL,
		`FIDE_ID`            int(8)       unsigned default NULL,
		`FIDE_Land`          char(3)               default NULL,
		PRIMARY KEY  (`ZPS`,`Mgl_Nr`),
		KEY `FIDE_ID` (`FIDE_ID`),
		KEY `Spielername_G` (`Spielername_G`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['dwz_verbaende'] = "CREATE TABLE IF NOT EXISTS `dwz_verbaende` (
		`Verband`            char(3)      NOT NULL default '',
		`LV`                 char(1)      NOT NULL default '',
		`Uebergeordnet`      char(3)      NOT NULL default '',
		`Verbandname`        varchar(45)  NOT NULL default '',
		PRIMARY KEY (`Verband`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['dwz_vereine'] = "CREATE TABLE IF NOT EXISTS `dwz_vereine` (
		`ZPS`                varchar(5)   NOT NULL default '',
		`LV`                 char(1)      NOT NULL default '',
		`Verband`            char(3)      NOT NULL default '',
		`Vereinname`         varchar(40)  NOT NULL default '',
		PRIMARY KEY (`ZPS`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_access_points'] = "CREATE TABLE IF NOT EXISTS `#__clm_access_points` (
		`id` int(11) NOT NULL auto_increment,
		`area` char(2) NOT NULL default 'BE',
		`accesstopic` varchar(20) NOT NULL,
		`accesspoint` varchar(20) NOT NULL,
		`rule` char(3) NOT NULL default 'NY',
		`published` int(1) NOT NULL default '0',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";

	$tableInsert['#__clm_access_points'] = "REPLACE INTO `#__clm_access_points` (`id`, `area`, `accesstopic`, `accesspoint`, `rule`, `published`, `ordering`) VALUES
		(1, 'BE', 'general', 'general', 'NY', 1, 1),
		(2, 'BE', 'season', 'general', 'NY', 1, 11),
		(3, 'BE', 'event', 'general', 'NY', 1, 21),
		(4, 'BE', 'event', 'delete', 'NY', 1, 24),
		(5, 'BE', 'tournament', 'general', 'NY', 1, 31),
		(6, 'BE', 'tournament', 'create', 'NY', 1, 32),
		(7, 'BE', 'tournament', 'edit_detail', 'NYT', 1, 33),
		(8, 'BE', 'tournament', 'delete', 'NY', 1, 34),
		(9, 'BE', 'tournament', 'edit_round', 'NYT', 1, 35),
		(10, 'BE', 'tournament', 'edit_result', 'NYT', 1, 36),
		(11, 'BE', 'tournament', 'edit_fixture', 'NYT', 1, 37),
		(12, 'BE', 'league', 'general', 'NY', 1, 41),
		(13, 'BE', 'league', 'create', 'NY', 1, 42),
		(14, 'BE', 'league', 'edit_detail', 'NYL', 1, 43),
		(15, 'BE', 'league', 'delete', 'NY', 1, 44),
		(16, 'BE', 'league', 'edit_round', 'NYL', 1, 45),
		(17, 'BE', 'league', 'edit_result', 'NYL', 1, 46),
		(18, 'BE', 'league', 'edit_fixture', 'NYL', 1, 47),
		(19, 'BE', 'teamtournament', 'general', 'NY', 1, 51),
		(20, 'BE', 'teamtournament', 'create', 'NY', 1, 52),
		(21, 'BE', 'teamtournament', 'edit_detail', 'NYT', 1, 53),
		(22, 'BE', 'teamtournament', 'delete', 'NY', 1, 54),
		(23, 'BE', 'teamtournament', 'edit_round', 'NYT', 1, 55),
		(24, 'BE', 'teamtournament', 'edit_result', 'NYT', 1, 56),
		(25, 'BE', 'teamtournament', 'edit_fixture', 'NYT', 1, 57),
		(26, 'BE', 'club', 'general', 'NY', 1, 61),
		(27, 'BE', 'club', 'create', 'NY', 1, 62),
		(28, 'BE', 'club', 'edit_member', 'NY', 1, 63),
		(29, 'BE', 'club', 'copy', 'NY', 1, 64),
		(30, 'BE', 'club', 'edit_ranking', 'NY', 1, 65),
		(31, 'BE', 'team', 'general', 'NY', 1, 71),
		(32, 'BE', 'team', 'create', 'NY', 1, 72),
		(33, 'BE', 'team', 'edit', 'NYL', 1, 73),
		(34, 'BE', 'team', 'delete', 'NY', 1, 74),
		(35, 'BE', 'team', 'registration_list', 'NYL', 1, 75),
		(36, 'BE', 'user', 'general', 'NY', 1, 81),
		(37, 'BE', 'user', 'copy', 'NY', 1, 84),
		(38, 'BE', 'accessgroup', 'general', 'NY', 1, 85),
		(39, 'BE', 'swt', 'general', 'NY', 1, 91),
		(40, 'BE', 'elobase', 'general', 'NY', 1, 101),
		(41, 'BE', 'database', 'general', 'NY', 1, 111),
		(42, 'BE', 'logfile', 'general', 'NY', 1, 121),
		(43, 'BE', 'logfile', 'delete', 'NY', 1, 122),
		(44, 'BE', 'config', 'general', 'NY', 1, 131);";
		
	$tableCreate['#__clm_categories'] = "CREATE TABLE IF NOT EXISTS `#__clm_categories` (
		`id` smallint(6) NOT NULL auto_increment,
		`parentid` smallint(6) unsigned default NULL,
		`name` varchar(100) NOT NULL default '',
		`sid` mediumint(3) unsigned default NULL,
		`dateStart` date NOT NULL,
		`dateEnd` date NOT NULL,
		`tl` mediumint(5) unsigned default NULL,
		`bezirk` varchar(8) default NULL,
		`bezirkTur` enum('0','1') NOT NULL default '1',
		`vereinZPS` varchar(5) default NULL,
		`published` mediumint(3) unsigned default NULL,
		`started` tinyint(1) NOT NULL default '0',
		`finished` tinyint(1) NOT NULL default '0',
		`invitationText` text,
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`params` text NOT NULL,
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_dwz_dewis'] = "CREATE TABLE IF NOT EXISTS `#__clm_dwz_dewis` (
		`id` int(11) NOT NULL auto_increment,
		`pkz` varchar(9) default NULL,
		`nachname` varchar(150) NOT NULL default '',
		`vorname` varchar(150) NOT NULL default '',
		`zps` varchar(5) NOT NULL default '',
		`mgl_nr` varchar(4) NOT NULL default '',
		`dwz` smallint(4) unsigned default NULL,
		`dwz_index` smallint(4) unsigned default NULL,
		`status` char(1) default NULL,
		`geschlecht` char(1) default NULL,
		`geburtsjahr` year(4) NOT NULL default '0000',
		`fide_elo` smallint(4) unsigned default NULL,
		`fide_land` char(3) default NULL,
		`fide_id` int(8) unsigned default NULL,
		`liga` smallint(4) unsigned default NULL,
		`turnier` smallint(4) unsigned default NULL,
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_dwz_dewis_merge'] = "CREATE TABLE IF NOT EXISTS `#__clm_dwz_dewis_merge` (
		`zps` varchar(5) NOT NULL default '',
		`mgl` varchar(4) NOT NULL default '',
		PRIMARY KEY  (`zps`,`mgl`)
	) ". $engine . $utf8 . ";";
	
	$tableCreate['#__clm_dwz_spieler'] = "CREATE TABLE IF NOT EXISTS `#__clm_dwz_spieler` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(6) unsigned default NULL,
		`PKZ` varchar(9) default NULL,
		`ZPS` varchar(5) NOT NULL default '',
		`Mgl_Nr` varchar(4) NOT NULL default '',
		`Status` char(1) default NULL,
		`Spielername` varchar(40) NOT NULL default '',
		`Spielername_G` varchar(40) NOT NULL default '',
		`Geschlecht` char(1) default NULL,
		`Spielberechtigung` char(1) NOT NULL default '',
		`Geburtsjahr` year(4) NOT NULL default '0000',
		`Letzte_Auswertung` mediumint(6) unsigned default NULL,
		`DWZ` smallint(4) unsigned default NULL,
		`DWZ_Index` smallint(3) unsigned default NULL,
		`FIDE_Elo` smallint(4) unsigned default NULL,
		`FIDE_Titel` char(2) default NULL,
		`FIDE_ID` int(8) unsigned default NULL,
		`FIDE_Land` char(3) default NULL,
		`DWZ_neu` smallint(4) unsigned NOT NULL default '0',
		`I0` smallint(4) unsigned NOT NULL default '0',
		`Punkte` decimal(4,1) unsigned NOT NULL default '0.0',
		`Partien` tinyint(3) NOT NULL default '0',
		`We` decimal(6,3) NOT NULL default '0.000',
		`Leistung` smallint(4) NOT NULL default '0',
		`EFaktor` tinyint(2) NOT NULL default '0',
		`Niveau` smallint(4) NOT NULL default '0',
		PRIMARY KEY  (`id`),
		UNIQUE KEY `sid_zps_mglnr` ( `sid`, `ZPS`, `Mgl_Nr` ),
		KEY `sid` (`sid`),
		KEY `ZPS` (`ZPS`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_dwz_vereine'] = "CREATE TABLE IF NOT EXISTS `#__clm_dwz_vereine` (
		`id` int(11) unsigned NOT NULL auto_increment,
		`sid` mediumint(6) unsigned default NULL,
		`ZPS` varchar(5) NOT NULL default '',
		`LV` char(1) NOT NULL default '',
		`Verband` varchar(3) NOT NULL default '',
		`Vereinname` varchar(40) NOT NULL default '',
		PRIMARY KEY  (`id`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_ergebnis'] = "CREATE TABLE IF NOT EXISTS `#__clm_ergebnis` (
		`id` int(11) NOT NULL auto_increment,
		`eid` mediumint(5) unsigned default NULL,
		`erg_text` varchar(10) NOT NULL default '',
		PRIMARY KEY  (`id`)
	) ".$engine . $utf8 . ";";
		
	$tableInsert['#__clm_ergebnis'] = "REPLACE INTO `#__clm_ergebnis` (`id`, `eid`, `erg_text`) VALUES
		(1, 0, '0-1'),
		(2, 1, '1-0'),
		(3, 2, '0,5-0,5'),
		(4, 3, '0-0'),
		(5, 4, '-/+'),
		(6, 5, '+/-'),
		(7, 6, '-/-'),
		(8, 7, '---'),
		(9, 8, 'spielfrei');";
		
	$tableCreate['#__clm_liga'] = "CREATE TABLE IF NOT EXISTS `#__clm_liga` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(100) NOT NULL default '',
		`sid` mediumint(3) unsigned default NULL,
		`teil` mediumint(5) unsigned default NULL,
		`stamm` mediumint(5) unsigned default NULL,
		`ersatz` mediumint(5) unsigned default NULL,
		`rang` tinyint(1) unsigned default 0,
		`sl` mediumint(5) unsigned default NULL,
		`runden` mediumint(5) unsigned default NULL,
		`durchgang` mediumint(5) unsigned default NULL,
		`mail` tinyint(1) unsigned default NULL,
		`sl_mail` tinyint(1) unsigned default NULL,
		`heim` tinyint(1) unsigned default NULL,
		`order` tinyint(1) unsigned default NULL,
		`rnd` tinyint(1) unsigned default NULL,
		`auf` tinyint(1) NOT NULL,
		`auf_evtl` tinyint(1) NOT NULL,
		`ab` tinyint(1) NOT NULL,
		`ab_evtl` tinyint(1) NOT NULL,
		`sieg_bed` tinyint(2) unsigned default NULL,
		`runden_modus` tinyint(2) unsigned default NULL,
		`man_sieg` decimal(4,2) unsigned default '1.0',
		`man_remis` decimal(4,2) unsigned default '0.5',
		`man_nieder` decimal(4,2) unsigned default '0.0',
		`man_antritt` decimal(4,2) unsigned default '0.0',
		`sieg` decimal(2,1) unsigned default '1.0',
		`remis` decimal(2,1) unsigned default '0.5',
		`nieder` decimal(2,1) unsigned default '0.0',
		`antritt` decimal(2,1) unsigned default '0.0',
		`published` mediumint(3) unsigned default NULL,
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`b_wertung` tinyint(1) unsigned default '0',
		`liga_mt` tinyint(1) unsigned default '0',
		`tiebr1` tinyint(2) unsigned NOT NULL default '0',
		`tiebr2` tinyint(2) unsigned NOT NULL default '0',
		`tiebr3` tinyint(2) unsigned NOT NULL default '0',		  
		`ersatz_regel` tinyint(1) unsigned default '0',
		`anzeige_ma` tinyint(1) unsigned default '0',
		`params` text NOT NULL,
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_log'] = "CREATE TABLE IF NOT EXISTS `#__clm_log` (
		`id` int(11) NOT NULL auto_increment,
		`aktion` varchar(100) NOT NULL default '',
		`jid_aktion` int(11) unsigned default NULL,
		`sid` int(11) unsigned default NULL,
		`catid` smallint(6) unsigned default NULL,
		`lid` int(11) unsigned default NULL,
		`tid` int(11) unsigned default NULL,
		`rnd` int(11) unsigned default NULL,
		`paar` int(11) unsigned default NULL,
		`dg` int(11) unsigned default NULL,
		`zps` varchar(5) default NULL,
		`man` int(11) unsigned default NULL,
		`mgl_nr` int(11) unsigned default NULL,
		`jid` int(11) unsigned default NULL,
		`cids` varchar(100) NOT NULL default '',
		`datum` datetime NOT NULL default '0000-00-00 00:00:00',
		`nr_aktion` smallint(6) ,
		PRIMARY KEY  (`id`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_mannschaften'] = "CREATE TABLE IF NOT EXISTS `#__clm_mannschaften` (
		`id` int(11) NOT NULL auto_increment,
		`sid` int(11) NOT NULL default '0',
		`name` varchar(100) NOT NULL default '',
		`liga` mediumint(5) unsigned default NULL,
		`zps` varchar(5) default NULL,
		`liste` mediumint(3) NOT NULL default '0',
		`edit_liste` mediumint(3) NOT NULL default '0',
		`man_nr` mediumint(5) unsigned default NULL,
		`tln_nr` mediumint(5) unsigned default NULL,
		`mf` mediumint(5) unsigned default NULL,
		`sg_zps` varchar(120) default NULL,
		`datum` datetime NOT NULL default '0000-00-00 00:00:00',
		`edit_datum` datetime NOT NULL default '0000-00-00 00:00:00',
		`lokal` text NOT NULL,
		`termine` text,
		`adresse` text,
		`homepage` text,
		`bemerkungen` text NOT NULL,
		`bem_int` text NOT NULL,
		`published` tinyint(1) NOT NULL default '0',
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`summanpunkte` decimal(4,1) default NULL,
		`sumbrettpunkte` decimal(4,1) default NULL,
		`sumwins` tinyint(2) default NULL,
		`sumtiebr1` decimal(6,3) default '0.000',
		`sumtiebr2` decimal(6,3) default '0.000',
		`sumtiebr3` decimal(6,3) default '0.000',
		`rankingpos` tinyint(3) unsigned NOT NULL default '0',
		`sname` varchar(20) NOT NULL default '',
		`abzug` tinyint(2) NOT NULL default '0',
		PRIMARY KEY  (`id`),
		KEY `published` (`published`),
		KEY `sid` (`sid`),		
		KEY `liga_sid` (`liga`,`sid`)		
	) ".$engine ." ROW_FORMAT=COMPRESSED ". $utf8 . ";";
		
	$tableCreate['#__clm_meldeliste_spieler'] = "CREATE TABLE IF NOT EXISTS `#__clm_meldeliste_spieler` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(3) unsigned default NULL,
		`lid` mediumint(3) unsigned default NULL,
		`mnr` mediumint(5) unsigned NOT NULL default '0',
		`snr` mediumint(5) unsigned default NULL,
		`mgl_nr` mediumint(5) unsigned NOT NULL default '0',
		`zps` varchar(5) NOT NULL default '0',
		`status` mediumint(5) NOT NULL default '0',
		`ordering` int(11) NOT NULL default '0',
		`start_dwz` smallint(4) unsigned default NULL,
		`start_I0` smallint(4) unsigned default NULL,
		`DWZ` smallint(4) unsigned NOT NULL default '0',
		`I0` smallint(4) unsigned NOT NULL default '0',
		`Punkte` decimal(4,1) unsigned NOT NULL default '0.0',
		`Partien` tinyint(3) NOT NULL default '0',
		`We` decimal(6,3) NOT NULL default '0.000',
		`Leistung` smallint(4) NOT NULL default '0',
		`EFaktor` tinyint(2) NOT NULL default '0',
		`Niveau` smallint(4) NOT NULL default '0',
		`sum_saison` decimal(5,1) NOT NULL default '0.0',
		`gesperrt` tinyint(1) unsigned DEFAULT NULL,
		PRIMARY KEY  (`id`),
		KEY `sid_zps_mglnr` ( `sid`, `zps`, `mgl_nr` )
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_params'] = "CREATE TABLE IF NOT EXISTS `#__clm_params` (
		`params` text NOT NULL,
		`id` tinyint(1) NOT NULL,
		PRIMARY KEY (`id`)			  
	) ".$engine . $utf8 . ";";
		 
	$tableCreate['#__clm_rangliste_id'] = "CREATE TABLE IF NOT EXISTS `#__clm_rangliste_id` (
		`id` int(10) unsigned NOT NULL auto_increment,
		`gid` int(10) unsigned NOT NULL default '0',
		`sid` mediumint(5) NOT NULL,
		`zps` varchar(5) NOT NULL default '00000',
		`rang` tinyint(1) NOT NULL,
		`published` mediumint(3) unsigned default NULL,
		`bemerkungen` text NOT NULL,
		`bem_int` text NOT NULL,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_rangliste_name'] = "CREATE TABLE IF NOT EXISTS `#__clm_rangliste_name` (
		`id` int(10) unsigned NOT NULL auto_increment,
		`Gruppe` varchar(30) character set utf8 collate utf8_bin NOT NULL,
		`Meldeschluss` date default '2009-06-30',
		`geschlecht` varchar(1) default NULL,
		`alter_grenze` varchar(1) default NULL,
		`alter` smallint(3) default NULL,
		`sid` mediumint(3) unsigned default '0',
		`user` mediumint(3) unsigned default '0',
		`user_clm` mediumint(3) unsigned default '0',
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`published` tinyint(1) NOT NULL default '0',
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";
		
	$tableInsert['#__clm_rangliste_name'] ="INSERT INTO `#__clm_rangliste_name` (`id`, `Gruppe`, `Meldeschluss`, `geschlecht`, `alter_grenze`, `alter`, `sid`, `user`, `user_clm`, `bemerkungen`, `bem_int`, `checked_out`, `checked_out_time`, `ordering`, `published`) VALUES
		(1, 'Testrangliste', '2011-12-31', '0', '0', 0, 1, 62, 100, '', '', 0, '0000-00-00 00:00:00', 1, 1);";
		
	$tableCreate['#__clm_rangliste_spieler'] = "CREATE TABLE IF NOT EXISTS `#__clm_rangliste_spieler` (
		`Gruppe` tinyint(3) unsigned NOT NULL,
		`ZPS` varchar(5) NOT NULL default '00000',
		`Mgl_Nr` smallint(5) unsigned NOT NULL default '0',
		`PKZ` int(10) unsigned NOT NULL default '0',
		`Rang` int(10) unsigned NOT NULL default '0',
		`man_nr` tinyint(3) unsigned NOT NULL default '1',
		`sid` mediumint(3) unsigned default '0',
		PRIMARY KEY  USING BTREE (`Gruppe`,`ZPS`,`man_nr`,`Rang`)
	) ". $engine . $utf8 . ";";
				
	$tableCreate['#__clm_rnd_man'] = "CREATE TABLE IF NOT EXISTS `#__clm_rnd_man` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(5) unsigned default NULL,
		`lid` mediumint(5) unsigned default NULL,
		`runde` mediumint(5) unsigned default NULL,
		`paar` mediumint(5) unsigned default NULL,
		`dg` tinyint(1) unsigned default NULL,
		`heim` tinyint(1) unsigned default NULL,
		`tln_nr` mediumint(5) unsigned NOT NULL default '0',
		`gegner` mediumint(5) unsigned NOT NULL default '0',
		`brettpunkte` decimal(5,1) unsigned default NULL,
		`manpunkte` mediumint(5) unsigned default NULL,
		`bp_sum` decimal(5,1) unsigned default NULL,
		`mp_sum` mediumint(5) unsigned default NULL,
		`gemeldet` mediumint(5) unsigned default NULL,
		`editor` mediumint(5) unsigned default NULL,
		`dwz_editor` mediumint(5) unsigned default NULL,
		`zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`edit_zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`dwz_zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`published` tinyint(1) unsigned NOT NULL default '0',
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`wertpunkte` decimal(5,1) unsigned default NULL,
		`ko_decision` tinyint(1) unsigned NOT NULL default '0',
		`comment` text NOT NULL,
		PRIMARY KEY  (`id`),
		KEY `lid_sid` (`lid`,`sid`),
		KEY `published` (`published`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_rnd_spl'] = "CREATE TABLE IF NOT EXISTS `#__clm_rnd_spl` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(5) unsigned default NULL,
		`lid` mediumint(5) unsigned default NULL,
		`runde` mediumint(5) unsigned default NULL,
		`paar` mediumint(5) unsigned default NULL,
		`dg` tinyint(1) unsigned default NULL,
		`tln_nr` mediumint(5) unsigned default NULL,
		`brett` mediumint(5) unsigned default NULL,
		`heim` tinyint(1) unsigned default NULL,
		`weiss` tinyint(1) unsigned default NULL,
		`spieler` mediumint(5) unsigned default NULL,
		`zps` varchar(5) default NULL,
		`gegner` mediumint(5) unsigned default NULL,
		`gzps` varchar(5) default NULL,
		`ergebnis` mediumint(5) unsigned default NULL,
		`kampflos` tinyint(1) unsigned default NULL,
		`punkte` decimal(5,1) unsigned default NULL,
		`gemeldet` mediumint(5) unsigned default NULL,
		`dwz_edit` mediumint(5) unsigned default NULL,
		`dwz_editor` mediumint(5) unsigned default NULL,
		PRIMARY KEY  (`id`),
		KEY `sid_zps_spieler` (`sid`,`zps`,`spieler`)
	) ".$engine . $utf8 . ";";
		
	$tableCreate['#__clm_runden_termine'] = "CREATE TABLE IF NOT EXISTS `#__clm_runden_termine` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(5) unsigned default NULL,
		`name` varchar(100) NOT NULL default '',
		`liga` mediumint(5) unsigned default NULL,
		`nr` mediumint(5) unsigned default NULL,
		`datum` date NOT NULL default '0000-00-00',
		`startzeit` time NOT NULL default '00:00:00',
		`deadlineday` date NOT NULL default '0000-00-00',
		`deadlinetime` time NOT NULL default '24:00:00',
		`meldung` tinyint(1)  NOT NULL default '0',
		`sl_ok` tinyint(1) NOT NULL default '0',
		`published` tinyint(1) NOT NULL default '0',
		`bemerkungen` text,
		`bem_int` text,
		`gemeldet` mediumint(3) unsigned default NULL,
		`dwz` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT '0',
		`editor` mediumint(3) unsigned default NULL,
		`zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`edit_zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ".$engine ." ROW_FORMAT=COMPRESSED ". $utf8 . ";";
		
	$tableCreate['#__clm_saison'] = "CREATE TABLE IF NOT EXISTS `#__clm_saison` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(100) NOT NULL default '',
		`published` tinyint(1) NOT NULL default '0',
		`archiv` tinyint(1) NOT NULL default '0',
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`datum` date NOT NULL default '0000-00-00', 
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ".$engine ." ROW_FORMAT=COMPRESSED ". $utf8 . ";";
		
	$tableInsert['#__clm_saison'] = "REPLACE #__clm_saison set id=1,name=concat(year(now())-(month(now())<7),'/',year(now())+(month(now())>6)),published=1;";
		
	$tableCreate['#__clm_swt_liga'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_liga` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`lid` int(11) DEFAULT NULL,
		`name` varchar(100) NOT NULL DEFAULT '',
		`sid` mediumint(3) unsigned DEFAULT NULL,
		`teil` mediumint(5) unsigned DEFAULT NULL,
		`stamm` mediumint(5) unsigned DEFAULT NULL,
		`ersatz` mediumint(5) unsigned DEFAULT NULL,
		`rang` tinyint(1) unsigned DEFAULT '0',
		`sl` mediumint(5) unsigned DEFAULT NULL,
		`runden` mediumint(5) unsigned DEFAULT NULL,
		`durchgang` mediumint(5) unsigned DEFAULT NULL,
		`mail` tinyint(1) unsigned DEFAULT NULL,
		`sl_mail` tinyint(1) unsigned DEFAULT NULL,
		`heim` tinyint(1) unsigned DEFAULT NULL,
		`order` tinyint(1) unsigned DEFAULT NULL,
		`rnd` tinyint(1) unsigned DEFAULT NULL,
		`auf` tinyint(1) NOT NULL,
		`auf_evtl` tinyint(1) NOT NULL,
		`ab` tinyint(1) NOT NULL,
		`ab_evtl` tinyint(1) NOT NULL,
		`sieg_bed` tinyint(2) unsigned DEFAULT NULL,
		`runden_modus` tinyint(2) unsigned DEFAULT NULL,
		`man_sieg` decimal(4,2) unsigned DEFAULT '1.00',
		`man_remis` decimal(4,2) unsigned DEFAULT '0.50',
		`man_nieder` decimal(4,2) unsigned DEFAULT '0.00',
		`man_antritt` decimal(4,2) unsigned DEFAULT '0.00',
		`sieg` decimal(2,1) unsigned DEFAULT '1.0',
		`remis` decimal(2,1) unsigned DEFAULT '0.5',
		`nieder` decimal(2,1) unsigned DEFAULT '0.0',
		`antritt` decimal(2,1) unsigned DEFAULT '0.0',
		`published` mediumint(3) unsigned DEFAULT NULL,
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`b_wertung` tinyint(1) unsigned DEFAULT '0',
		`liga_mt` tinyint(1) unsigned DEFAULT '0',
		`tiebr1` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`tiebr2` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`tiebr3` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`params` text NOT NULL,
		PRIMARY KEY (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_swt_mannschaften'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_mannschaften` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` int(11) NOT NULL DEFAULT '0',
		`name` varchar(100) NOT NULL DEFAULT '',
		`swt_id` mediumint(5) unsigned DEFAULT NULL,
		`liga` mediumint(5) unsigned DEFAULT NULL,
		`zps` varchar(5) DEFAULT NULL,
		`liste` mediumint(3) NOT NULL DEFAULT '0',
		`edit_liste` mediumint(3) NOT NULL DEFAULT '0',
		`man_nr` mediumint(5) unsigned DEFAULT NULL,
		`tln_nr` mediumint(5) unsigned DEFAULT NULL,
		`mf` mediumint(5) unsigned DEFAULT NULL,
		`sg_zps` varchar(120) DEFAULT NULL,
		`datum` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`edit_datum` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`lokal` text NOT NULL,
		`termine` text,
		`adresse` text,
		`homepage` text,
		`bemerkungen` text NOT NULL,
		`bem_int` text NOT NULL,
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`summanpunkte` decimal(4,1) DEFAULT NULL,
		`sumbrettpunkte` decimal(4,1) DEFAULT NULL,
		`sumwins` tinyint(2) DEFAULT NULL,
		`sumtiebr1` decimal(6,3) DEFAULT '0.000',
		`sumtiebr2` decimal(6,3) DEFAULT '0.000',
		`sumtiebr3` decimal(6,3) DEFAULT '0.000',
		`rankingpos` tinyint(3) unsigned NOT NULL DEFAULT '0',
		PRIMARY KEY (`id`),
		UNIQUE KEY `sid_name_swtid` (`sid`,`name`,`swt_id`),
		KEY `published` (`published`),
		KEY `sid` (`sid`),
		KEY `swt_id` (`swt_id`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_swt_meldeliste_spieler'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_meldeliste_spieler` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`spielerid` smallint(6) unsigned NOT NULL,
		`sid` mediumint(3) unsigned DEFAULT NULL,
		`swt_id` mediumint(5) unsigned DEFAULT NULL,
		`lid` mediumint(5) unsigned DEFAULT NULL,
		`man_id` mediumint(5) unsigned NOT NULL DEFAULT '0',
		`snr` mediumint(5) unsigned DEFAULT NULL,
		`mgl_nr` mediumint(5) unsigned NOT NULL DEFAULT '0',
		`zps` varchar(5) NOT NULL DEFAULT '0',
		`status` mediumint(5) NOT NULL DEFAULT '0',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`DWZ` smallint(4) unsigned NOT NULL DEFAULT '0',
		`I0` smallint(4) unsigned NOT NULL DEFAULT '0',
		`Punkte` decimal(4,1) unsigned NOT NULL DEFAULT '0.0',
		`Partien` tinyint(3) NOT NULL DEFAULT '0',
		`We` decimal(6,3) NOT NULL DEFAULT '0.000',
		`Leistung` smallint(4) NOT NULL DEFAULT '0',
		`EFaktor` tinyint(2) NOT NULL DEFAULT '0',
		`Niveau` smallint(4) NOT NULL DEFAULT '0',
		`sum_saison` decimal(5,1) NOT NULL DEFAULT '0.0',
		`gesperrt` tinyint(1) unsigned DEFAULT NULL,
		PRIMARY KEY (`id`),
		UNIQUE KEY `sid_swtid_manid_zps_mglnr` (`sid`,`swt_id`,`man_id`,`zps`,`mgl_nr`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_swt_rnd_man'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_rnd_man` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` mediumint(5) unsigned DEFAULT NULL,
		`swt_id` mediumint(5) unsigned DEFAULT NULL,
		`lid` mediumint(5) unsigned DEFAULT NULL,
		`runde` mediumint(5) unsigned DEFAULT NULL,
		`paar` mediumint(5) unsigned DEFAULT NULL,
		`dg` tinyint(1) unsigned DEFAULT NULL,
		`heim` tinyint(1) unsigned DEFAULT NULL,
		`tln_nr` mediumint(5) unsigned NOT NULL DEFAULT '0',
		`gegner` mediumint(5) unsigned NOT NULL DEFAULT '0',
		`brettpunkte` decimal(5,1) unsigned DEFAULT NULL,
		`manpunkte` mediumint(5) unsigned DEFAULT NULL,
		`bp_sum` decimal(5,1) unsigned DEFAULT NULL,
		`mp_sum` mediumint(5) unsigned DEFAULT NULL,
		`gemeldet` mediumint(5) unsigned DEFAULT NULL,
		`editor` mediumint(5) unsigned DEFAULT NULL,
		`dwz_editor` mediumint(5) unsigned DEFAULT NULL,
		`zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`edit_zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`dwz_zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`published` tinyint(1) unsigned NOT NULL DEFAULT '0',
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`wertpunkte` decimal(5,1) unsigned DEFAULT NULL,
		`ko_decision` tinyint(1) unsigned NOT NULL DEFAULT '0',
		`comment` text NOT NULL,
		PRIMARY KEY (`id`),
		KEY `published` (`published`),
		KEY `swt_id` (`swt_id`)
	) ". $engine . $utf8 . ";";
		 
	$tableCreate['#__clm_swt_rnd_spl'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_rnd_spl` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` mediumint(5) unsigned DEFAULT NULL,
		`swt_id` mediumint(5) unsigned DEFAULT NULL,
		`lid` mediumint(5) unsigned DEFAULT NULL,
		`runde` mediumint(5) unsigned DEFAULT NULL,
		`paar` mediumint(5) unsigned DEFAULT NULL,
		`dg` tinyint(1) unsigned DEFAULT NULL,
		`tln_nr` mediumint(5) unsigned DEFAULT NULL,
		`brett` mediumint(5) unsigned DEFAULT NULL,
		`heim` tinyint(1) unsigned DEFAULT NULL,
		`weiss` tinyint(1) unsigned DEFAULT NULL,
		`spieler` mediumint(5) unsigned DEFAULT NULL,
		`zps` varchar(5) DEFAULT NULL,
		`gegner` mediumint(5) unsigned DEFAULT NULL,
		`gzps` varchar(5) DEFAULT NULL,
		`ergebnis` mediumint(5) unsigned DEFAULT NULL,
		`kampflos` tinyint(1) unsigned DEFAULT NULL,
		`punkte` decimal(5,1) unsigned DEFAULT NULL,
		`gemeldet` mediumint(5) unsigned DEFAULT NULL,
		`dwz_edit` mediumint(5) unsigned DEFAULT NULL,
		`dwz_editor` mediumint(5) unsigned DEFAULT NULL,
		PRIMARY KEY (`id`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_swt_turniere'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_turniere` (
		`swt_tid` int(11) NOT NULL AUTO_INCREMENT,
		`tid` int(11) NOT NULL DEFAULT '0',
		`name` varchar(100) NOT NULL DEFAULT '',
		`sid` mediumint(3) unsigned DEFAULT NULL,
		`dateStart` date NOT NULL,
		`dateEnd` date NOT NULL,
		`catidAlltime` smallint(6) unsigned NOT NULL DEFAULT '0',
		`catidEdition` smallint(6) unsigned NOT NULL DEFAULT '0',
		`typ` tinyint(1) unsigned DEFAULT NULL,
		`tiebr1` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`tiebr2` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`tiebr3` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`rnd` tinyint(1) unsigned DEFAULT NULL,
		`teil` mediumint(5) unsigned DEFAULT NULL,
		`runden` mediumint(5) unsigned DEFAULT NULL,
		`dg` mediumint(5) unsigned DEFAULT NULL,
		`tl` mediumint(5) unsigned DEFAULT NULL,
		`bezirk` varchar(8) DEFAULT NULL,
		`bezirkTur` enum('0','1') NOT NULL DEFAULT '1',
		`vereinZPS` varchar(5) DEFAULT NULL,
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`started` tinyint(1) NOT NULL DEFAULT '0',
		`finished` tinyint(1) NOT NULL DEFAULT '0',
		`invitationText` text,
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`params` text NOT NULL,
		PRIMARY KEY (`swt_tid`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_swt_turniere_rnd_spl'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_turniere_rnd_spl` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` mediumint(5) unsigned DEFAULT NULL,
		`turnier` mediumint(5) unsigned DEFAULT NULL,
		`swt_tid` mediumint(5) unsigned DEFAULT NULL,
		`runde` mediumint(5) unsigned DEFAULT NULL,
		`paar` mediumint(5) unsigned DEFAULT NULL,
		`brett` mediumint(5) unsigned DEFAULT NULL,
		`dg` tinyint(1) unsigned DEFAULT NULL,
		`tln_nr` mediumint(5) unsigned DEFAULT NULL,
		`heim` tinyint(1) unsigned DEFAULT NULL,
		`spieler` mediumint(5) unsigned DEFAULT NULL,
		`gegner` mediumint(5) unsigned DEFAULT NULL,
		`ergebnis` mediumint(5) unsigned DEFAULT NULL,
		`tiebrS` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`tiebrG` tinyint(2) unsigned NOT NULL DEFAULT '0',
		`kampflos` tinyint(1) unsigned DEFAULT NULL,
		`pgn` text NOT NULL,
		`ordering` int(11) NOT NULL DEFAULT '0',
		PRIMARY KEY (`id`),
		UNIQUE KEY `turnier_dg_runde_brett_heim` (`swt_tid`,`dg`,`runde`,`brett`,`heim`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_swt_turniere_rnd_termine'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_turniere_rnd_termine` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` mediumint(5) unsigned DEFAULT NULL,
		`name` varchar(100) NOT NULL DEFAULT '',
		`turnier` mediumint(5) unsigned DEFAULT NULL,
		`swt_tid` mediumint(5) unsigned DEFAULT NULL,
		`dg` tinyint(1) unsigned DEFAULT NULL,
		`nr` mediumint(5) unsigned DEFAULT NULL,
		`datum` date NOT NULL DEFAULT '0000-00-00',
		`startzeit` time NOT NULL default '00:00:00',
		`abgeschlossen` mediumint(3) NOT NULL DEFAULT '0',
		`tl_ok` tinyint(1) NOT NULL DEFAULT '0',
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`bemerkungen` text,
		`bem_int` text,
		`gemeldet` mediumint(3) unsigned DEFAULT NULL,
		`editor` mediumint(3) unsigned DEFAULT NULL,
		`zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`edit_zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		PRIMARY KEY (`id`),
		UNIQUE KEY `turnier_dg_runde` (`swt_tid`,`dg`,`nr`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
			
	$tableCreate['#__clm_swt_turniere_tlnr'] = "CREATE TABLE IF NOT EXISTS `#__clm_swt_turniere_tlnr` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`sid` mediumint(3) unsigned DEFAULT NULL,
		`turnier` mediumint(4) unsigned DEFAULT NULL,
		`swt_tid` mediumint(4) unsigned DEFAULT NULL,
		`snr` mediumint(5) unsigned DEFAULT NULL,
		`name` varchar(150) DEFAULT NULL,
		`birthYear` year(4) NOT NULL DEFAULT '0000',
		`geschlecht` char(1) DEFAULT NULL,
		`verein` varchar(150) DEFAULT NULL,
		`twz` smallint(4) unsigned DEFAULT NULL,
		`NATrating` smallint(4) unsigned DEFAULT NULL,
		`FIDEelo` smallint(4) unsigned DEFAULT NULL,
		`FIDEid` int(8) unsigned DEFAULT NULL,
		`FIDEcco` char(3) DEFAULT NULL,
		`titel` char(3) DEFAULT NULL,
		`mgl_nr` mediumint(5) unsigned NOT NULL DEFAULT '0',
		`zps` varchar(5) NOT NULL DEFAULT '0',
		`status` mediumint(5) NOT NULL DEFAULT '0',
		`rankingPos` smallint(5) unsigned NOT NULL DEFAULT '0',
		`sum_punkte` decimal(4,1) DEFAULT NULL,
		`sum_bhlz` decimal(5,2) DEFAULT NULL,
		`sum_busum` decimal(6,2) DEFAULT NULL,
		`sum_sobe` decimal(5,2) DEFAULT NULL,
		`sum_wins` tinyint(1) unsigned NOT NULL DEFAULT '0',
		`sumTiebr1` decimal(6,3) DEFAULT NULL,
		`sumTiebr2` decimal(6,3) DEFAULT NULL,
		`sumTiebr3` decimal(6,3) DEFAULT NULL,
		`koStatus` enum('0','1') NOT NULL DEFAULT '1',
		`koRound` tinyint(1) unsigned NOT NULL DEFAULT '0',
		`DWZ` smallint(4) unsigned NOT NULL DEFAULT '0',
		`I0` smallint(4) unsigned NOT NULL DEFAULT '0',
		`Punkte` decimal(4,1) unsigned NOT NULL DEFAULT '0.0',
		`Partien` tinyint(3) NOT NULL DEFAULT '0',
		`We` decimal(6,3) NOT NULL DEFAULT '0.000',
		`Leistung` smallint(4) NOT NULL DEFAULT '0',
		`EFaktor` tinyint(2) NOT NULL DEFAULT '0',
		`Niveau` smallint(4) NOT NULL DEFAULT '0',
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`checked_out` tinyint(3) unsigned NOT NULL DEFAULT '0',
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		PRIMARY KEY (`id`,`zps`,`mgl_nr`,`status`),
		UNIQUE KEY `turnier_snr` (`swt_tid`,`snr`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_termine'] = "CREATE TABLE IF NOT EXISTS `#__clm_termine` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(100) NOT NULL default '',
		`beschreibung` text,
		`address` varchar(100) NOT NULL default '',
		`category` varchar(33) NOT NULL default '',
		`host` varchar(5) default NULL,
		`startdate` date NOT NULL default '0000-00-00 00:00:00',
		`starttime` time NOT NULL default '00:00:00',
		`allday` tinyint(3) NOT NULL default '0',
		`enddate` date NOT NULL default '0000-00-00 00:00:00',
		`endtime` time NOT NULL default '00:00:00',
		`noendtime` tinyint(3) NOT NULL default '0',
		`attached_file` varchar(256) NULL default '',
		`attached_file_description` varchar(128) NULL default '',
		`published` mediumint(3) unsigned default NULL,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`event_link` varchar(500) NOT NULL default '',
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_turniere'] = "CREATE TABLE IF NOT EXISTS `#__clm_turniere` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(100) NOT NULL default '',
		`sid` mediumint(3) unsigned default NULL,
		`dateStart` DATE NOT NULL,
		`dateEnd` DATE NOT NULL,
		`catidAlltime` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
		`catidEdition` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
		`typ` tinyint(1) unsigned default NULL,
		`tiebr1` tinyint(2) unsigned NOT NULL default '0',
		`tiebr2` tinyint(2) unsigned NOT NULL default '0',
		`tiebr3` tinyint(2) unsigned NOT NULL default '0',
		`rnd` tinyint(1) unsigned default NULL,
		`teil` mediumint(5) unsigned default NULL,
		`runden` mediumint(5) unsigned default NULL,
		`dg` mediumint(5) unsigned default NULL,
		`tl` mediumint(5) unsigned default NULL,
		`bezirk` varchar(8) default NULL,
		`bezirkTur` enum('0','1') NOT NULL default '1',
		`vereinZPS` varchar(5) default NULL,
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`started` tinyint(1) NOT NULL DEFAULT '0',
		`finished` tinyint(1) NOT NULL DEFAULT '0',
		`invitationText` text,
		`bemerkungen` text,
		`bem_int` text,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`params` text NOT NULL,
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_turniere_rnd_spl'] = "CREATE TABLE IF NOT EXISTS `#__clm_turniere_rnd_spl` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(5) unsigned default NULL,
		`turnier` mediumint(5) unsigned default NULL,
		`runde` mediumint(5) unsigned default NULL,
		`paar` mediumint(5) unsigned default NULL,
		`brett` mediumint(5) unsigned default NULL,
		`dg` tinyint(1) unsigned default NULL,
		`tln_nr` mediumint(5) unsigned default NULL,
		`heim` tinyint(1) unsigned default NULL,
		`spieler` mediumint(5) unsigned default NULL,
		`gegner` mediumint(5) unsigned default NULL,
		`ergebnis` mediumint(5) unsigned default NULL,
		`tiebrS` decimal(2,1) unsigned NOT NULL DEFAULT '0.0',
		`tiebrG` decimal(2,1) unsigned NOT NULL DEFAULT '0.0',
		`kampflos` tinyint(1) unsigned default NULL,
		`gemeldet` mediumint(3) unsigned default NULL,
		`pgn` text NOT NULL,
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_turniere_rnd_termine'] = "CREATE TABLE IF NOT EXISTS `#__clm_turniere_rnd_termine` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(5) unsigned default NULL,
		`name` varchar(100) NOT NULL default '',
		`turnier` mediumint(5) unsigned default NULL,
		`dg` tinyint(1) unsigned default NULL,
		`nr` mediumint(5) unsigned default NULL,
		`datum` date NOT NULL default '0000-00-00',
		`startzeit` time NOT NULL default '00:00:00',
		`abgeschlossen` mediumint(3) NOT NULL default '0',
		`tl_ok` tinyint(1) NOT NULL default '0',
		`published` tinyint(1) NOT NULL default '0',
		`bemerkungen` text,
		`bem_int` text,
		`gemeldet` mediumint(3) unsigned default NULL,
		`editor` mediumint(3) unsigned default NULL,
		`zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`edit_zeit` datetime NOT NULL default '0000-00-00 00:00:00',
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";

	$tableCreate['#__clm_turniere_sonderranglisten'] = "CREATE TABLE IF NOT EXISTS `#__clm_turniere_sonderranglisten` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`turnier` int(11) NOT NULL,
		`name` varchar(100) NOT NULL,
		`use_rating_filter` enum('0','1') DEFAULT '0',
		`rating_type` tinyint(1) DEFAULT '0',
		`rating_higher_than` smallint(4) DEFAULT '0',
		`rating_lower_than` smallint(4) DEFAULT '3000',
		`use_birthYear_filter` enum('0','1') DEFAULT '0',
		`birthYear_younger_than` year(4) DEFAULT '0000',
		`birthYear_older_than` year(4) DEFAULT '0000',
		`use_sex_filter` enum('0','1') DEFAULT '0',
		`sex` enum('','M','W') DEFAULT NULL,
		`published` tinyint(1) NOT NULL DEFAULT '0',
		`checked_out` tinyint(3) unsigned NOT NULL,
		`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL DEFAULT '0',
		`use_zps_filter` enum('0','1') DEFAULT '0',
		`zps_higher_than` varchar(5) DEFAULT '',
		`zps_lower_than` varchar(5) DEFAULT 'ZZZZZ',
		`use_sex_year_filter` enum('0','1') DEFAULT '0',
		`maleYear_younger_than` year(4) DEFAULT '0000',
		`maleYear_older_than` year(4) DEFAULT '0000',
		`femaleYear_younger_than` year(4) DEFAULT '0000',
		`femaleYear_older_than` year(4) DEFAULT '0000',
		PRIMARY KEY (`id`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_turniere_tlnr'] = "CREATE TABLE IF NOT EXISTS `#__clm_turniere_tlnr` (
		`id` int(11) NOT NULL auto_increment,
		`sid` mediumint(3) unsigned default NULL,
		`turnier` mediumint(4) unsigned default NULL,
		`snr` mediumint(5) unsigned default NULL,
		`name` varchar(150) default NULL,
		`birthYear` year(4) NOT NULL DEFAULT '0000',
		`geschlecht` CHAR(1) DEFAULT NULL,		
		`verein` varchar(150) default NULL,
		`twz` smallint(4) unsigned default NULL,
		`NATrating` smallint(4) UNSIGNED NULL,
		`FIDEelo` smallint(4) UNSIGNED NULL,
		`FIDEid` int(8) UNSIGNED NULL,
		`FIDEcco` char(3) NULL,
		`titel` char(3) default NULL,
		`mgl_nr` mediumint(5) unsigned NOT NULL default '0',
		`zps` varchar(5) NOT NULL default '0',
		`status` mediumint(5) NOT NULL default '0',
		`rankingPos` smallint(5) UNSIGNED NOT NULL default '0',
		`tlnrStatus` tinyint(1) UNSIGNED NOT NULL default '1',
		`anz_spiele` tinyint(2) UNSIGNED NOT NULL default '0',
		`sum_punkte` decimal(4,1) default NULL,
		`sum_bhlz` decimal(5,2) default NULL,
		`sum_busum` decimal(6,2) default NULL,
		`sum_sobe` decimal(5,2) default NULL,
		`sum_wins` tinyint(1) unsigned NOT NULL default '0',
		`sumTiebr1` DECIMAL(8, 3) DEFAULT NULL,
		`sumTiebr2` DECIMAL(8, 3) DEFAULT NULL,
		`sumTiebr3` DECIMAL(8, 3) DEFAULT NULL,
		`koStatus` enum( '0', '1' ) NOT NULL default '1',
		`koRound` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT '0',
		`DWZ` smallint(4) unsigned NOT NULL default '0',
		`I0` smallint(4) unsigned NOT NULL default '0',
		`Punkte` decimal(4,1) unsigned NOT NULL default '0.0',
		`Partien` tinyint(3) NOT NULL default '0',
		`We` decimal(6,3) NOT NULL default '0.000',
		`Leistung` smallint(4) NOT NULL default '0',
		`EFaktor` tinyint(2) NOT NULL default '0',
		`Niveau` smallint(4) NOT NULL default '0',
		`published` tinyint(1) NOT NULL default '0',
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`,`zps`,`mgl_nr`,`status`),
		KEY `turnier_snr` (`turnier`,`snr`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_user'] = "CREATE TABLE IF NOT EXISTS `#__clm_user` (
		`id` int(11) NOT NULL auto_increment,
		`sid` smallint(3) unsigned default NULL,
		`jid` mediumint(5) unsigned default NULL,
		`name` text NOT NULL,
		`username` varchar(150) NOT NULL default '',
		`aktive` tinyint(3) NOT NULL default '0',
		`email` varchar(100) NOT NULL default '',
		`tel_fest` varchar(30) NOT NULL default '',
		`tel_mobil` varchar(30) NOT NULL default '',
		`usertype` varchar(75) NOT NULL default '',
		`user_clm` smallint(3) unsigned default NULL,
		`zps` varchar(5) default NULL,
		`mglnr` varchar(4) default NULL,
 		`mannschaft` smallint(3) unsigned default NULL,
		`published` smallint(3) unsigned default NULL,
		`bemerkungen` text NOT NULL,
		`bem_int` text NOT NULL,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		`block` tinyint(4) NOT NULL default '0',
		`activation` varchar(100) NOT NULL default '',
		PRIMARY KEY  (`id`),
		KEY `sid_jid` ( `sid`, `jid` ),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
		
	$tableCreate['#__clm_usertype'] = "CREATE TABLE IF NOT EXISTS `#__clm_usertype` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(200) NOT NULL default '',
		`user_clm` smallint(3) unsigned default NULL,
		`kind` varchar(4) NOT NULL default 'USER',
		`usertype` varchar(15) default '0',
		`published` int(1) NOT NULL default '0',
		`ordering` int(11) NOT NULL default '0',
		`fe_params` text NOT NULL,
		`be_params` text NOT NULL,
		PRIMARY KEY  (`id`)
	) ". $engine . $utf8 . ";";
				
	$tableCreate['#__clm_vereine'] = "CREATE TABLE IF NOT EXISTS `#__clm_vereine` (
		`id` int(11) NOT NULL auto_increment,
		`name` varchar(100) NOT NULL default '',
		`sid` mediumint(5) unsigned default NULL,
		`zps` varchar(5) default NULL,
		`vl` mediumint(5) unsigned default NULL,
		`lokal` varchar(200) NOT NULL default '',
		`homepage` varchar(200) NOT NULL default '',
		`adresse` varchar(200) NOT NULL default '',
		`vs` varchar(200) NOT NULL default '',
		`vs_mail` varchar(200) NOT NULL default '',
		`vs_tel` varchar(200) NOT NULL default '',
		`tl` varchar(200) NOT NULL default '',
		`tl_mail` varchar(200) NOT NULL default '',
		`tl_tel` varchar(200) NOT NULL default '',
		`jw` varchar(200) NOT NULL default '',
		`jw_mail` varchar(200) NOT NULL default '',
		`jw_tel` varchar(200) NOT NULL default '',
		`pw` varchar(200) NOT NULL default '',
		`pw_mail` varchar(200) NOT NULL default '',
		`pw_tel` varchar(200) NOT NULL default '',
		`kw` varchar(200) NOT NULL default '',
		`kw_mail` varchar(200) NOT NULL default '',
		`kw_tel` varchar(200) NOT NULL default '',
		`sw` varchar(200) NOT NULL default '',
		`sw_mail` varchar(200) NOT NULL default '',
		`sw_tel` varchar(200) NOT NULL default '',
		`termine` varchar(200) NOT NULL default '',
		`published` mediumint(3) unsigned default NULL,
		`bemerkungen` text NOT NULL,
		`bem_int` text NOT NULL,
		`checked_out` tinyint(3) unsigned NOT NULL default '0',
		`checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
		`ordering` int(11) NOT NULL default '0',
		PRIMARY KEY  (`id`),
		KEY `published` (`published`)
	) ". $engine . $utf8 . ";";
		

	

		$database = SimpleClmInstaller::_getDB();
		
		foreach ($tableCreate as $key => $sql) {
			$database->setQuery($sql);
			if ( !$database->query() ) {
				echo "Fehler beim Anlegen der Tabelle ".$key;
				return false;
			}
		}
		foreach ($tableInsert as $key => $sql) {
			$database->setQuery($sql);
			if ( !$database->query() ) {
				echo "Fehler beim Füllen der Tabelle ".$key;
				return false;
			}
		}
		
		//return "* Tabellen erfolgreich angelegt!<br />";
		//}
		
?>
