REPLACE INTO `dwz_verbaende` VALUES ('000','0','000','Deutscher Schachbund e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('100','1','000','Badischer Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('101','1','100','-- Bezirk Mannheim');
REPLACE INTO `dwz_verbaende` VALUES ('102','1','100','-- Bezirk Heidelberg');
REPLACE INTO `dwz_verbaende` VALUES ('103','1','100','-- Bezirk Odenwald');
REPLACE INTO `dwz_verbaende` VALUES ('104','1','100','-- Bezirk Karlsruhe');
REPLACE INTO `dwz_verbaende` VALUES ('105','1','100','-- Bezirk Pforzheim');
REPLACE INTO `dwz_verbaende` VALUES ('106','1','100','-- Bezirk Mittelbaden');
REPLACE INTO `dwz_verbaende` VALUES ('107','1','100','-- Bezirk Ortenau');
REPLACE INTO `dwz_verbaende` VALUES ('108','1','100','-- Bezirk Freiburg');
REPLACE INTO `dwz_verbaende` VALUES ('109','1','100','-- Bezirk Hochrhein');
REPLACE INTO `dwz_verbaende` VALUES ('10A','1','100','-- Bezirk Schwarzwald');
REPLACE INTO `dwz_verbaende` VALUES ('10B','1','100','-- Bezirk Bodensee');
REPLACE INTO `dwz_verbaende` VALUES ('200','2','000','Bayerischer Schachbund');
REPLACE INTO `dwz_verbaende` VALUES ('210','2','200','- Bezirk Mittelfranken');
REPLACE INTO `dwz_verbaende` VALUES ('211','2','210','--- Kreis Mittelfranken-Mitte');
REPLACE INTO `dwz_verbaende` VALUES ('212','2','210','--- Kreis Mittelfranken-Nord');
REPLACE INTO `dwz_verbaende` VALUES ('213','2','210','--- Kreis Mittelfranken-Ost');
REPLACE INTO `dwz_verbaende` VALUES ('214','2','210','--- Kreis Mittelfranken-Süd');
REPLACE INTO `dwz_verbaende` VALUES ('215','2','210','--- Kreis Mittelfranken-West');
REPLACE INTO `dwz_verbaende` VALUES ('220','2','200','- Bezirk München');
REPLACE INTO `dwz_verbaende` VALUES ('230','2','200','- Bezirk Niederbayern');
REPLACE INTO `dwz_verbaende` VALUES ('240','2','200','- Bezirk Oberbayern');
REPLACE INTO `dwz_verbaende` VALUES ('241','2','240','--- Kreis Ingolstadt/Freising');
REPLACE INTO `dwz_verbaende` VALUES ('242','2','240','--- Kreis Inn-Chiemgau');
REPLACE INTO `dwz_verbaende` VALUES ('244','2','240','--- Kreis Zugspitze');
REPLACE INTO `dwz_verbaende` VALUES ('250','2','200','- Bezirk Oberfranken');
REPLACE INTO `dwz_verbaende` VALUES ('251','2','250','--- Kreis Bamberg');
REPLACE INTO `dwz_verbaende` VALUES ('252','2','250','--- Kreis Bayreuth');
REPLACE INTO `dwz_verbaende` VALUES ('253','2','250','--- Kreis Hof');
REPLACE INTO `dwz_verbaende` VALUES ('254','2','250','--- Kreis Coburg/Neustadt');
REPLACE INTO `dwz_verbaende` VALUES ('255','2','250','--- Kreis Marktredwitz');
REPLACE INTO `dwz_verbaende` VALUES ('256','2','250','--- Kreis Lichtenfels/Kronach');
REPLACE INTO `dwz_verbaende` VALUES ('260','2','200','- Bezirk Oberpfalz');
REPLACE INTO `dwz_verbaende` VALUES ('270','2','200','- Bezirk Schwaben');
REPLACE INTO `dwz_verbaende` VALUES ('271','2','270','--- Kreis Augsburg');
REPLACE INTO `dwz_verbaende` VALUES ('272','2','270','--- Kreis Mittelschwaben');
REPLACE INTO `dwz_verbaende` VALUES ('273','2','270','--- Kreis Nordschwaben');
REPLACE INTO `dwz_verbaende` VALUES ('274','2','270','--- Kreis Südschwaben');
REPLACE INTO `dwz_verbaende` VALUES ('280','2','200','- Bezirk Unterfranken');
REPLACE INTO `dwz_verbaende` VALUES ('281','2','280','--- Kreis Spessart-Untermain');
REPLACE INTO `dwz_verbaende` VALUES ('282','2','280','--- Kreis Mainspessart');
REPLACE INTO `dwz_verbaende` VALUES ('283','2','280','--- Kreis Haßberge-Rhön');
REPLACE INTO `dwz_verbaende` VALUES ('284','2','280','--- Kreis Maindreieck');
REPLACE INTO `dwz_verbaende` VALUES ('300','3','000','Berliner Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('400','4','000','Hamburger Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('500','5','000','Hessischer Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('510','5','500','-- Bezirk Kassel-Nordhessen');
REPLACE INTO `dwz_verbaende` VALUES ('520','5','500','-- Bezirk Osthessen');
REPLACE INTO `dwz_verbaende` VALUES ('530','5','500','-- Bezirk Lahn-Eder');
REPLACE INTO `dwz_verbaende` VALUES ('540','5','500','-- Bezirk Main-Vogelsberg');
REPLACE INTO `dwz_verbaende` VALUES ('550','5','500','-- Bezirk Frankfurt/Main');
REPLACE INTO `dwz_verbaende` VALUES ('560','5','500','-- Bezirk Starkenburg');
REPLACE INTO `dwz_verbaende` VALUES ('570','5','500','-- Bezirk Main-Taunus');
REPLACE INTO `dwz_verbaende` VALUES ('580','5','500','-- Bezirk Mittelrhein');
REPLACE INTO `dwz_verbaende` VALUES ('590','5','500','-- Bezirk Lahn');
REPLACE INTO `dwz_verbaende` VALUES ('5A0','5','500','-- Bezirk Bergstraße');
REPLACE INTO `dwz_verbaende` VALUES ('600','6','000','Schachbund Nordrhein-Westfalen');
REPLACE INTO `dwz_verbaende` VALUES ('610','6','600','- Schachverband Ruhrgebiet');
REPLACE INTO `dwz_verbaende` VALUES ('611','6','610','--- Bochum');
REPLACE INTO `dwz_verbaende` VALUES ('612','6','610','--- SG Dortmund');
REPLACE INTO `dwz_verbaende` VALUES ('613','6','610','--- Bezirk Essen');
REPLACE INTO `dwz_verbaende` VALUES ('614','6','610','--- Emscher-Lippe');
REPLACE INTO `dwz_verbaende` VALUES ('615','6','610','--- Hamm');
REPLACE INTO `dwz_verbaende` VALUES ('616','6','610','--- Bezirk Mülheim');
REPLACE INTO `dwz_verbaende` VALUES ('617','6','610','--- Vestischer Schachkreis');
REPLACE INTO `dwz_verbaende` VALUES ('618','6','610','--- Herne');
REPLACE INTO `dwz_verbaende` VALUES ('620','6','600','- Schachverband Niederrhein');
REPLACE INTO `dwz_verbaende` VALUES ('621','6','620','--- Bergisch-Land');
REPLACE INTO `dwz_verbaende` VALUES ('622','6','620','--- Düsseldorf');
REPLACE INTO `dwz_verbaende` VALUES ('623','6','620','--- Duisburg');
REPLACE INTO `dwz_verbaende` VALUES ('624','6','620','--- Linker Niederrhein');
REPLACE INTO `dwz_verbaende` VALUES ('625','6','620','--- Wesel');
REPLACE INTO `dwz_verbaende` VALUES ('630','6','600','- Schachverband Südwestfalen');
REPLACE INTO `dwz_verbaende` VALUES ('632','6','630','--- Iserlohn');
REPLACE INTO `dwz_verbaende` VALUES ('633','6','630','--- Oberberg');
REPLACE INTO `dwz_verbaende` VALUES ('634','6','630','--- Hochsauerland');
REPLACE INTO `dwz_verbaende` VALUES ('635','6','630','--- Sauerland');
REPLACE INTO `dwz_verbaende` VALUES ('636','6','630','--- Siegerland');
REPLACE INTO `dwz_verbaende` VALUES ('640','6','600','- Schachverband Ostwestfalen-Lippe');
REPLACE INTO `dwz_verbaende` VALUES ('641','6','640','--- Bielefeld');
REPLACE INTO `dwz_verbaende` VALUES ('642','6','640','--- Hellweg');
REPLACE INTO `dwz_verbaende` VALUES ('643','6','640','--- Lippe');
REPLACE INTO `dwz_verbaende` VALUES ('644','6','640','--- Porta');
REPLACE INTO `dwz_verbaende` VALUES ('645','6','640','--- Teutoburger Wald-West');
REPLACE INTO `dwz_verbaende` VALUES ('650','6','600','- Schachverband Münsterland');
REPLACE INTO `dwz_verbaende` VALUES ('651','6','650','--- Steinfurt');
REPLACE INTO `dwz_verbaende` VALUES ('652','6','650','--- Borken');
REPLACE INTO `dwz_verbaende` VALUES ('653','6','650','--- Münster');
REPLACE INTO `dwz_verbaende` VALUES ('660','6','600','- Schachverband Mittelrhein');
REPLACE INTO `dwz_verbaende` VALUES ('661','6','660','--- Aachener Schachverband von 1928');
REPLACE INTO `dwz_verbaende` VALUES ('662','6','660','--- Bonn/Rhein-Sieg e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('663','6','660','--- Kölner Schachverband von 1852');
REPLACE INTO `dwz_verbaende` VALUES ('664','6','660','--- Rur-Erft');
REPLACE INTO `dwz_verbaende` VALUES ('665','6','660','--- Rhein-Wupper');
REPLACE INTO `dwz_verbaende` VALUES ('700','7','000','Niedersächsischer Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('701','7','700','-- Bezirk 1 Hannover');
REPLACE INTO `dwz_verbaende` VALUES ('702','7','700','-- Bezirk 2 Braunschweig');
REPLACE INTO `dwz_verbaende` VALUES ('703','7','700','-- Bezirk 3 Südniedersachsen');
REPLACE INTO `dwz_verbaende` VALUES ('704','7','700','-- Bezirk 4 Lüneburg');
REPLACE INTO `dwz_verbaende` VALUES ('705','7','700','-- Bezirk 5 Oldenburg-Ostfriesland');
REPLACE INTO `dwz_verbaende` VALUES ('706','7','700','-- Bezirk 6 Osnabrück-Emsland');
REPLACE INTO `dwz_verbaende` VALUES ('800','8','000','Schachbund Rheinland-Pfalz e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('810','8','800','- Schachbund Rheinland e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('811','8','810','--- Bezirk I Rhein-Ahr-Mosel');
REPLACE INTO `dwz_verbaende` VALUES ('812','8','810','--- Bezirk II Rhein-Nahe');
REPLACE INTO `dwz_verbaende` VALUES ('813','8','810','--- Bezirk III Rhein-Westerwald');
REPLACE INTO `dwz_verbaende` VALUES ('815','8','810','--- Bezirk IV Trier');
REPLACE INTO `dwz_verbaende` VALUES ('820','8','800','- Schachbund Rheinhessen e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('830','8','800','- Pfälzischer Schachbund e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('831','8','830','--- Bezirk I Kaiserslautern');
REPLACE INTO `dwz_verbaende` VALUES ('832','8','830','--- Bezirk II Ludwigshafen');
REPLACE INTO `dwz_verbaende` VALUES ('833','8','830','--- Bezirk III Neustadt');
REPLACE INTO `dwz_verbaende` VALUES ('834','8','830','--- Bezirk IV Landau');
REPLACE INTO `dwz_verbaende` VALUES ('835','8','830','--- Bezirk V Pirmasens');
REPLACE INTO `dwz_verbaende` VALUES ('836','8','830','--- Bezirk VI Ramstein');
REPLACE INTO `dwz_verbaende` VALUES ('900','9','000','Saarländischer Schachverband');
REPLACE INTO `dwz_verbaende` VALUES ('A00','A','000','Schachverband Schleswig-Holstein');
REPLACE INTO `dwz_verbaende` VALUES ('A01','A','A00','-- Bezirk I Nord');
REPLACE INTO `dwz_verbaende` VALUES ('A02','A','A00','-- Bezirk II West');
REPLACE INTO `dwz_verbaende` VALUES ('A04','A','A00','-- Bezirk IV Süd');
REPLACE INTO `dwz_verbaende` VALUES ('A05','A','A00','-- Bezirk V Lübeck');
REPLACE INTO `dwz_verbaende` VALUES ('A06','A','A00','-- Bezirk VI Kiel');
REPLACE INTO `dwz_verbaende` VALUES ('B00','B','000','Landesschachbund Bremen');
REPLACE INTO `dwz_verbaende` VALUES ('C00','C','000','Schachverband Württemberg e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('C01','C','C00','-- Bezirk Oberschwaben');
REPLACE INTO `dwz_verbaende` VALUES ('C02','C','C00','-- Bezirk Alb-Schwarzwald');
REPLACE INTO `dwz_verbaende` VALUES ('C03','C','C00','-- Bezirk Neckar/Fils');
REPLACE INTO `dwz_verbaende` VALUES ('C04','C','C00','-- Bezirk Ostalb');
REPLACE INTO `dwz_verbaende` VALUES ('C05','C','C00','-- Bezirk Stuttgart');
REPLACE INTO `dwz_verbaende` VALUES ('C06','C','C00','-- Bezirk Unterland');
REPLACE INTO `dwz_verbaende` VALUES ('D00','D','000','Schachbund Brandenburg');
REPLACE INTO `dwz_verbaende` VALUES ('D10','D','D00','-- Bezirk Cottbus');
REPLACE INTO `dwz_verbaende` VALUES ('D20','D','D00','-- Bezirk Frankfurt/Oder');
REPLACE INTO `dwz_verbaende` VALUES ('D30','D','D00','-- Bezirk Potsdam');
REPLACE INTO `dwz_verbaende` VALUES ('E00','E','000','LSV Mecklenburg-Vorpommern');
REPLACE INTO `dwz_verbaende` VALUES ('E01','E','E00','-- Spielbezirk West');
REPLACE INTO `dwz_verbaende` VALUES ('E02','E','E00','-- Spielbezirk Mitte');
REPLACE INTO `dwz_verbaende` VALUES ('E03','E','E00','-- Spielbezirk Ost');
REPLACE INTO `dwz_verbaende` VALUES ('F00','F','000','Schachverband Sachsen e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('F10','F','F00','- Bezirk Leipzig');
REPLACE INTO `dwz_verbaende` VALUES ('F11','F','F10','--- Kreis Delitzsch');
REPLACE INTO `dwz_verbaende` VALUES ('F12','F','F10','--- Kreis Döbeln');
REPLACE INTO `dwz_verbaende` VALUES ('F13','F','F10','--- Kreis Torgau-Oschatz');
REPLACE INTO `dwz_verbaende` VALUES ('F15','F','F10','--- Kreis Leipzig-Stadt');
REPLACE INTO `dwz_verbaende` VALUES ('F18','F','F10','--- Kreis Leipzig-Land');
REPLACE INTO `dwz_verbaende` VALUES ('F19','F','F10','--- Kreis Muldentalkreis');
REPLACE INTO `dwz_verbaende` VALUES ('F20','F','F00','- Bezirk Dresden');
REPLACE INTO `dwz_verbaende` VALUES ('F21','F','F20','--- Kreis Riesa-Großenhain');
REPLACE INTO `dwz_verbaende` VALUES ('F22','F','F20','--- Kreis Sächsische Schweiz');
REPLACE INTO `dwz_verbaende` VALUES ('F23','F','F20','--- Kreis Kamenz');
REPLACE INTO `dwz_verbaende` VALUES ('F24','F','F20','--- Kreis Hoyerswerda');
REPLACE INTO `dwz_verbaende` VALUES ('F25','F','F20','--- Kreis Weißeritzkreis');
REPLACE INTO `dwz_verbaende` VALUES ('F26','F','F20','--- Kreis Meißen');
REPLACE INTO `dwz_verbaende` VALUES ('F27','F','F20','--- Kreis Görlitz');
REPLACE INTO `dwz_verbaende` VALUES ('F28','F','F20','--- Kreis Dresden');
REPLACE INTO `dwz_verbaende` VALUES ('F29','F','F20','--- Kreis Löbau-Zittau');
REPLACE INTO `dwz_verbaende` VALUES ('F2A','F','F20','--- Kreis Bautzen');
REPLACE INTO `dwz_verbaende` VALUES ('F2B','F','F20','--- Niederschlesischer Oberlausitzkreis');
REPLACE INTO `dwz_verbaende` VALUES ('F30','F','F00','- Bezirk Chemnitz');
REPLACE INTO `dwz_verbaende` VALUES ('F31','F','F30','--- Kreis Stollberg');
REPLACE INTO `dwz_verbaende` VALUES ('F32','F','F30','--- Kreis Mittweida');
REPLACE INTO `dwz_verbaende` VALUES ('F33','F','F30','--- Kreis Freiberg');
REPLACE INTO `dwz_verbaende` VALUES ('F34','F','F30','--- Kreis Chemnitzer Land');
REPLACE INTO `dwz_verbaende` VALUES ('F35','F','F30','--- Kreis Annaberg-Buchholz');
REPLACE INTO `dwz_verbaende` VALUES ('F36','F','F30','--- Kreis Chemnitz');
REPLACE INTO `dwz_verbaende` VALUES ('F37','F','F30','--- Kreis Vogtlandkreis');
REPLACE INTO `dwz_verbaende` VALUES ('F38','F','F30','--- Kreis Zwickau');
REPLACE INTO `dwz_verbaende` VALUES ('F39','F','F30','--- Mittlerer Erzgebirgskreis');
REPLACE INTO `dwz_verbaende` VALUES ('F3A','F','F30','--- Kreis Zwickauer Land');
REPLACE INTO `dwz_verbaende` VALUES ('F3B','F','F30','--- Kreis Plauen');
REPLACE INTO `dwz_verbaende` VALUES ('F3C','F','F30','--- Kreis Aue-Schwarzenberg');
REPLACE INTO `dwz_verbaende` VALUES ('G00','G','000','LSV Sachsen-Anhalt e.V.');
REPLACE INTO `dwz_verbaende` VALUES ('G10','G','G00','-- Schachbezirk Dessau');
REPLACE INTO `dwz_verbaende` VALUES ('G20','G','G00','-- Schachbezirk Halle');
REPLACE INTO `dwz_verbaende` VALUES ('G30','G','G00','-- Schachbezirk Magdeburg');
REPLACE INTO `dwz_verbaende` VALUES ('H00','H','000','Thüringer Schachbund');
REPLACE INTO `dwz_verbaende` VALUES ('H10','H','H00','- Schachbezirk Nord');
REPLACE INTO `dwz_verbaende` VALUES ('H11','H','H10','--- Schachkreis Kyffhäuser');
REPLACE INTO `dwz_verbaende` VALUES ('H12','H','H10','--- Schachkreis Eichsfeld');
REPLACE INTO `dwz_verbaende` VALUES ('H13','H','H10','--- Schachkreis Nordhausen');
REPLACE INTO `dwz_verbaende` VALUES ('H14','H','H10','--- Schachkreis Unstrut-Hainich');
REPLACE INTO `dwz_verbaende` VALUES ('H15','H','H10','--- Schachkreis Gotha');
REPLACE INTO `dwz_verbaende` VALUES ('H20','H','H00','- Schachbezirk Mitte');
REPLACE INTO `dwz_verbaende` VALUES ('H21','H','H20','--- Schachkreis Erfurt');
REPLACE INTO `dwz_verbaende` VALUES ('H22','H','H20','--- Schachkreis Apolda');
REPLACE INTO `dwz_verbaende` VALUES ('H23','H','H20','--- Schachkreis Sömmerda');
REPLACE INTO `dwz_verbaende` VALUES ('H24','H','H20','--- Schachkreis Ilmkreis');
REPLACE INTO `dwz_verbaende` VALUES ('H25','H','H20','--- Schachkreis Weimar');
REPLACE INTO `dwz_verbaende` VALUES ('H30','H','H00','- Schachbezirk Ost');
REPLACE INTO `dwz_verbaende` VALUES ('H31','H','H30','--- Schachkreis Gera');
REPLACE INTO `dwz_verbaende` VALUES ('H32','H','H30','--- Schachkreis Jena/Holzlandkreis');
REPLACE INTO `dwz_verbaende` VALUES ('H33','H','H30','--- Schachkreis Greiz');
REPLACE INTO `dwz_verbaende` VALUES ('H34','H','H30','--- Schachkreis Altenburger Land');
REPLACE INTO `dwz_verbaende` VALUES ('H35','H','H30','--- Schachkreis Saalfeld/Rudolstadt');
REPLACE INTO `dwz_verbaende` VALUES ('H40','H','H00','- Schachbezirk Süd');
REPLACE INTO `dwz_verbaende` VALUES ('H41','H','H40','--- Schachkreis Schmalkalden/Meiningen');
REPLACE INTO `dwz_verbaende` VALUES ('H43','H','H40','--- Schachkreis Wartburgkreis');
REPLACE INTO `dwz_verbaende` VALUES ('L00','L','000','Deutscher Blindenschachbund');
